/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package bugapp.gui;

import bugapp.connection.GmailConnection;
import bugapp.persistence.dao.AsergSurveyDAO;
import bugapp.persistence.entity.AsergSurvey;
import bugapp.util.DateUtil;
import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.StringSelection;

/**
 *
 * @author Henrique
 */
public class EmailDialog extends javax.swing.JDialog {

    private AsergSurvey Subject;
    
    /**
     * Creates new form EmailDialog
     */
    public EmailDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txaEmail = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        btnCopyToClipboard = new javax.swing.JButton();
        btnBugLink = new javax.swing.JButton();
        btnDevLink = new javax.swing.JButton();
        btnMarkAsSent = new javax.swing.JButton();
        btnSent = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtDevEmail = new javax.swing.JTextField();
        btnCopySendTo = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txfSubject = new javax.swing.JTextField();
        CopySubject = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModal(true);
        setPreferredSize(new java.awt.Dimension(800, 600));
        setType(java.awt.Window.Type.POPUP);

        txaEmail.setColumns(20);
        txaEmail.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        txaEmail.setRows(5);
        jScrollPane1.setViewportView(txaEmail);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        btnCopyToClipboard.setText("Copy to Clipboard");
        btnCopyToClipboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCopyToClipboardActionPerformed(evt);
            }
        });
        jPanel1.add(btnCopyToClipboard);

        btnBugLink.setText("Copy Buglink");
        btnBugLink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBugLinkActionPerformed(evt);
            }
        });
        jPanel1.add(btnBugLink);

        btnDevLink.setText("Copy DevLink");
        btnDevLink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDevLinkActionPerformed(evt);
            }
        });
        jPanel1.add(btnDevLink);

        btnMarkAsSent.setText("Mark as Sent");
        btnMarkAsSent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMarkAsSentActionPerformed(evt);
            }
        });
        jPanel1.add(btnMarkAsSent);

        btnSent.setText("Send");
        btnSent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSentActionPerformed(evt);
            }
        });
        jPanel1.add(btnSent);

        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        jPanel1.add(btnClose);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jPanel2.setLayout(new java.awt.GridLayout(2, 1));

        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEADING));

        jLabel1.setText("Send to:");
        jLabel1.setPreferredSize(new java.awt.Dimension(45, 14));
        jPanel3.add(jLabel1);

        txtDevEmail.setPreferredSize(new java.awt.Dimension(250, 25));
        jPanel3.add(txtDevEmail);

        btnCopySendTo.setText("Copy to Clipboard");
        btnCopySendTo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCopySendToActionPerformed(evt);
            }
        });
        jPanel3.add(btnCopySendTo);

        jPanel2.add(jPanel3);

        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEADING));

        jLabel2.setText("Subject: ");
        jLabel2.setPreferredSize(new java.awt.Dimension(45, 14));
        jPanel4.add(jLabel2);

        txfSubject.setText("Academic Research on Bug Reports");
        txfSubject.setPreferredSize(new java.awt.Dimension(250, 25));
        jPanel4.add(txfSubject);

        CopySubject.setText("Copy to Clipboard");
        CopySubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CopySubjectActionPerformed(evt);
            }
        });
        jPanel4.add(CopySubject);

        jPanel2.add(jPanel4);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnMarkAsSentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMarkAsSentActionPerformed
        try{
            //System.out.println("Updating Db...");
            AsergSurveyDAO.updateStatus(Subject, AsergSurveyDAO.SurveyStatus.SENT);
            //System.out.println("Done.");
            
        }catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_btnMarkAsSentActionPerformed

    private void btnCopyToClipboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCopyToClipboardActionPerformed
        try{
            copyToClipboard(txaEmail.getText());
        }catch(Exception e){
            System.out.println(e);
        }
        
    }//GEN-LAST:event_btnCopyToClipboardActionPerformed

    private void btnBugLinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBugLinkActionPerformed
        try{
            String Link = "https://bugzilla.mozilla.org/show_bug.cgi?id="+Subject.getBugId();
            copyToClipboard(Link);
        }catch(Exception e){
            System.out.println(e);
        }

    }//GEN-LAST:event_btnBugLinkActionPerformed

    private void btnDevLinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDevLinkActionPerformed
        try{
            String Link = "https://bugzilla.mozilla.org/user_profile?login="+Subject.getDevLogin();
            copyToClipboard(Link);
        }catch(Exception e){
            System.out.println(e);
        }

    }//GEN-LAST:event_btnDevLinkActionPerformed

    private void CopySubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CopySubjectActionPerformed
        copyToClipboard(txfSubject.getText());
    }//GEN-LAST:event_CopySubjectActionPerformed

    private void btnCopySendToActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCopySendToActionPerformed
        copyToClipboard(txtDevEmail.getText());
    }//GEN-LAST:event_btnCopySendToActionPerformed

    private void btnSentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSentActionPerformed
        try{
            GmailConnection gmail = new GmailConnection("henrique.rocha@gmail.com", "ramapnjtcbo1");
            gmail.sendTSL("H. Rocha <henrique.rocha@dcc.ufmg.br>", txtDevEmail.getText(), "Academic Research on Bug Reports", txaEmail.getText());
            AsergSurveyDAO.updateStatus(Subject, AsergSurveyDAO.SurveyStatus.SENT);
            this.setVisible(false);
            
        }catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_btnSentActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(EmailDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(EmailDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(EmailDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(EmailDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                EmailDialog dialog = new EmailDialog(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CopySubject;
    private javax.swing.JButton btnBugLink;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnCopySendTo;
    private javax.swing.JButton btnCopyToClipboard;
    private javax.swing.JButton btnDevLink;
    private javax.swing.JButton btnMarkAsSent;
    private javax.swing.JButton btnSent;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txaEmail;
    private javax.swing.JTextField txfSubject;
    private javax.swing.JTextField txtDevEmail;
    // End of variables declaration//GEN-END:variables

    public void copyToClipboard(String Text){
        StringSelection ssel = new StringSelection(Text);
        Clipboard cpb = Toolkit.getDefaultToolkit().getSystemClipboard();
        cpb.setContents(ssel, ssel);
    }
    
    
    /**
     * @return the Subject
     */
    public AsergSurvey getSubject() {
        return Subject;
    }

    /**
     * @param Subject the Subject to set
     */
    public void setSubject(AsergSurvey Subject) {
        this.Subject = Subject;
        
        String txt = createEmail(Subject);
        txaEmail.setText(txt);
        txaEmail.setCaretPosition(0);
        
        txtDevEmail.setText( Subject.getDevLogin() );
    }
    
    public static String createEmail(AsergSurvey S){
        StringBuilder stb = new StringBuilder();
        stb.append("Hello Mr./Ms. ");
        stb.append(S.getDevName());
        stb.append(",\n\n");
        
        java.sql.Date Dt = DateUtil.addDate(S.getDtSurvey(), -1);
        
        stb.append("I am a PhD Student at UFMG, Brazil, working with bug reports.\n\n");
        stb.append("As part of my research, I am monitoring the bugs fixed on each day at Mozilla. For example, I found that the following bug assigned to you was resolved yesterday (");
        stb.append(DateUtil.getSqlDateAsString(Dt, "yyyy-MM-dd"));
        stb.append(")\n\n");
        
        stb.append("https://bugzilla.mozilla.org/show_bug.cgi?id=");
        stb.append(S.getBugId());
        stb.append(" - ");
        stb.append(S.getShortDesc());
        stb.append("\n\n");
        
        stb.append("If you could, please answer a few questions for my research:\n\n");
        stb.append("QUESTION 1:\n");
        stb.append("Why did you choose this bug to work on? (you may mark more than one option if applicable)\n");
        
        stb.append("a. (    ) It is similar to bugs I usually fix.\n");
        stb.append("b. (    ) It was assigned to me by someone (e.g. project manager).\n");
        stb.append("c. (    ) It was blocking another bug.\n");
        stb.append("d. (    ) It was a bug with a high priority.\n");
        stb.append("e. (    ) Other reason: __________________ \n");

//        stb.append("a. (    ) I usually fix bugs related to this Mozilla's component/feature.\n");
//        stb.append("b. (    ) It is similar to bugs I fixed in the past\n");
//        stb.append("c. (    ) It was assigned to me by someone (e.g. project manager) \n");
        
        stb.append("\n");
        stb.append("QUESTION 2:\n");
        stb.append("Do you have the freedom to chose which bugs to address? \n");
        stb.append("(    ) Yes, I choose myself most bugs I resolved\n");
        stb.append("(    ) No, most bugs are usually assigned to me\n");
        
        stb.append("\n");
        stb.append("QUESTION 3:\n");
        stb.append(" - If you answered yes to question (2), please describe how do you usually choose the next bug to work on.\n");
        stb.append(" - If you answered no to question (2), please describe how would you choose the next bug to work on (assuming you had this freedom).\n");
        stb.append("\n");
        stb.append("QUESTION 4 (Optional):\n");
        stb.append("Please describe any other relevant information regarding the process you follow to select the next bug to work on.\n");
        stb.append("\n");
        stb.append("\n");
        stb.append("All information you provide will be kept private. \n");
        stb.append("\n");
        stb.append("Thank you in advance for your collaboration.\n\n");
        stb.append("- Henrique Rocha\n");
        stb.append("CS PhD Student (UFMG - Brazil)\n");
        stb.append("ASERG Research Group <http://aserg.labsoft.dcc.ufmg.br/>\n");
        
        return stb.toString();
    }
    
}
