/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ProfilesBugsPanel.java
 *
 * Created on Dec 10, 2012, 3:25:20 PM
 */
package bugapp.gui;

import bugapp.persistence.dao.BugsDAO;
import bugapp.persistence.dao.ProfilesDAO;
import bugapp.persistence.entity.BugComponent;
import bugapp.persistence.entity.Profile;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Henrique
 */
public class ProfilesBugsPanel extends javax.swing.JPanel {

    /** Creates new form ProfilesBugsPanel */
    public ProfilesBugsPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProfiles = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblBugs = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txfBeginDate = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        txfEndDate = new javax.swing.JFormattedTextField();

        setLayout(new java.awt.BorderLayout());

        jSplitPane1.setDividerLocation(250);
        jSplitPane1.setOneTouchExpandable(true);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Developers"));
        jPanel2.setLayout(new java.awt.BorderLayout());

        tblProfiles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Login", "Bugs"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblProfiles);

        jPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jButton2.setText("Find Bugs from Selected Developer");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, java.awt.BorderLayout.PAGE_END);

        jSplitPane1.setLeftComponent(jPanel2);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Bugs & Components"));
        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.LINE_AXIS));

        tblBugs.setAutoCreateRowSorter(true);
        tblBugs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Bug", "CompId", "CompName", "Product", "Creation", "Resolved"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblBugs);

        jPanel3.add(jScrollPane2);

        jSplitPane1.setRightComponent(jPanel3);

        add(jSplitPane1, java.awt.BorderLayout.CENTER);

        jPanel1.setMinimumSize(new java.awt.Dimension(278, 40));
        jPanel1.setPreferredSize(new java.awt.Dimension(660, 40));

        jButton1.setText("Search Developers");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);

        jLabel1.setText("Begin Date:");
        jPanel1.add(jLabel1);

        txfBeginDate.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("d/M/yy"))));
        txfBeginDate.setText("01/09/2009");
        txfBeginDate.setPreferredSize(new java.awt.Dimension(80, 20));
        jPanel1.add(txfBeginDate);

        jLabel2.setText("   End Date:");
        jPanel1.add(jLabel2);

        txfEndDate.setText("31/09/2012");
        txfEndDate.setPreferredSize(new java.awt.Dimension(80, 20));
        jPanel1.add(txfEndDate);

        add(jPanel1, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        try{
            ArrayList<Profile> lst = ProfilesDAO.getProfilesAssignedToBugsWithCount(null, null);
            DefaultTableModel dtm = (DefaultTableModel) tblProfiles.getModel();
            for(Profile P : lst){
                Object[] Row = new Object[3];
                Row[0]=P.getId();
                Row[1]=P.getLogin();
                Row[2]=P.getQuantidadeBugs();
                dtm.addRow(Row);
            }
            
        }catch(Exception e){
            System.out.println(e);
            JOptionPane.showMessageDialog(this, e);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            int RowIndex = tblProfiles.getSelectedRow();
            if (RowIndex >= 0) {
                Integer UserId = (Integer) tblProfiles.getModel().getValueAt(RowIndex, 0);

                DateFormat F = new SimpleDateFormat("dd/MM/yyyy");
                java.util.Date DtBegin = F.parse(getBeginDate());
                java.util.Date DtEnd = F.parse(getEndDate());
                //System.out.println(UserId);

                ArrayList<BugComponent> lst = BugsDAO.getDevelBugComponents(UserId, DtBegin, DtEnd);
                DefaultTableModel dtm = (DefaultTableModel) tblBugs.getModel();
                dtm.setRowCount(0);
                //dtm.
                for (BugComponent B : lst) {
                    Object[] Row = new Object[6];
                    Row[0] = B.getId();
                    Row[1] = B.getComponentId();
                    Row[2] = B.getComponentName();
                    Row[3] = B.getProductName();
                    Row[4] = B.getCreation();
                    Row[5] = B.getLastResolved();
                    dtm.addRow(Row);
                }
            }
        } catch (Exception e) {
            System.out.println(e);
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    public String getBeginDate(){
        return txfBeginDate.getText();
    }
    
    public String getEndDate(){
        return txfEndDate.getText();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTable tblBugs;
    private javax.swing.JTable tblProfiles;
    private javax.swing.JFormattedTextField txfBeginDate;
    private javax.swing.JFormattedTextField txfEndDate;
    // End of variables declaration//GEN-END:variables
}
