/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package bugapp.gui;

import bugapp.connection.MozillaConnection;
import bugapp.persistence.dao.AsergSurveyDAO;
import bugapp.persistence.entity.AsergSurvey;
import java.awt.Dialog;
import java.sql.Timestamp;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Henrique
 */
public class SurveyDialog extends javax.swing.JDialog {

    protected AsergSurveyTableModel dtmSurvey = new AsergSurveyTableModel();
    protected static String EmailTemplate="";
    
    /**
     * Creates new form SurveyDialog
     * @param parent
     * @param modal
     */
    public SurveyDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgStatus = new javax.swing.ButtonGroup();
        jToolBar1 = new javax.swing.JToolBar();
        btnMapInfo = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btnEmail = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        btnChangeStatus = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        btnSaveAnswer = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        btnThanksEmail = new javax.swing.JButton();
        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSurveySubjects = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txfDate = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        rdbPending = new javax.swing.JRadioButton();
        rdbSent = new javax.swing.JRadioButton();
        rdbAnswered = new javax.swing.JRadioButton();
        rdbExcluded = new javax.swing.JRadioButton();
        rdbOther = new javax.swing.JRadioButton();
        rdbAll = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        txfBugClause = new javax.swing.JTextField();
        btnReadFromDB = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblStatusBar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Mozilla Survey Dialog");
        setPreferredSize(new java.awt.Dimension(800, 600));

        jToolBar1.setRollover(true);

        btnMapInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bugapp/gui/resources/connect-icon.png"))); // NOI18N
        btnMapInfo.setToolTipText("Connect and Get Info");
        btnMapInfo.setFocusable(false);
        btnMapInfo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMapInfo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnMapInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMapInfoActionPerformed(evt);
            }
        });
        jToolBar1.add(btnMapInfo);
        jToolBar1.add(jSeparator1);

        btnEmail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bugapp/gui/resources/mail-icon.png"))); // NOI18N
        btnEmail.setToolTipText("Email Dialog");
        btnEmail.setFocusable(false);
        btnEmail.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEmail.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmailActionPerformed(evt);
            }
        });
        jToolBar1.add(btnEmail);
        jToolBar1.add(jSeparator2);

        btnChangeStatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bugapp/gui/resources/change-status-icon.png"))); // NOI18N
        btnChangeStatus.setToolTipText("Change Status");
        btnChangeStatus.setFocusable(false);
        btnChangeStatus.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnChangeStatus.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnChangeStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeStatusActionPerformed(evt);
            }
        });
        jToolBar1.add(btnChangeStatus);
        jToolBar1.add(jSeparator3);

        btnSaveAnswer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bugapp/gui/resources/answer-icon.png"))); // NOI18N
        btnSaveAnswer.setToolTipText("Save Answer");
        btnSaveAnswer.setFocusable(false);
        btnSaveAnswer.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSaveAnswer.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSaveAnswer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveAnswerActionPerformed(evt);
            }
        });
        jToolBar1.add(btnSaveAnswer);
        jToolBar1.add(jSeparator4);

        btnThanksEmail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bugapp/gui/resources/thanks-icon.png"))); // NOI18N
        btnThanksEmail.setToolTipText("Thanks Email");
        btnThanksEmail.setFocusable(false);
        btnThanksEmail.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnThanksEmail.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnThanksEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThanksEmailActionPerformed(evt);
            }
        });
        jToolBar1.add(btnThanksEmail);

        getContentPane().add(jToolBar1, java.awt.BorderLayout.PAGE_START);

        jSplitPane1.setDividerLocation(80);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane1.setLastDividerLocation(80);
        jSplitPane1.setOneTouchExpandable(true);

        tblSurveySubjects.setAutoCreateRowSorter(true);
        tblSurveySubjects.setModel(dtmSurvey);
        jScrollPane1.setViewportView(tblSurveySubjects);
        initTableComp();

        jSplitPane1.setRightComponent(jScrollPane1);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("DB Search"));
        jPanel1.setMaximumSize(new java.awt.Dimension(150, 32767));

        jLabel1.setText("Date >=");
        jPanel1.add(jLabel1);

        txfDate.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("yyyy-MM-dd"))));
        txfDate.setText("2015-02-09");
        jPanel1.add(txfDate);

        jLabel2.setText("Status:");
        jPanel1.add(jLabel2);

        btgStatus.add(rdbPending);
        rdbPending.setSelected(true);
        rdbPending.setText("Pending");
        jPanel1.add(rdbPending);

        btgStatus.add(rdbSent);
        rdbSent.setText("Sent  ");
        jPanel1.add(rdbSent);

        btgStatus.add(rdbAnswered);
        rdbAnswered.setText("Answered");
        jPanel1.add(rdbAnswered);

        btgStatus.add(rdbExcluded);
        rdbExcluded.setText("Excluded");
        jPanel1.add(rdbExcluded);

        btgStatus.add(rdbOther);
        rdbOther.setText("Other");
        jPanel1.add(rdbOther);

        btgStatus.add(rdbAll);
        rdbAll.setText("All");
        jPanel1.add(rdbAll);

        jLabel3.setText("      #bugs");
        jPanel1.add(jLabel3);

        txfBugClause.setText(">=27");
        jPanel1.add(txfBugClause);

        btnReadFromDB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bugapp/gui/resources/search-icon.png"))); // NOI18N
        btnReadFromDB.setText("Search");
        btnReadFromDB.setFocusable(false);
        btnReadFromDB.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        btnReadFromDB.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnReadFromDB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReadFromDBActionPerformed(evt);
            }
        });
        jPanel1.add(btnReadFromDB);

        jSplitPane1.setLeftComponent(jPanel1);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Status Bar"));

        lblStatusBar.setText("...");
        jPanel2.add(lblStatusBar);

        getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReadFromDBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReadFromDBActionPerformed
        readFromDb();
    }//GEN-LAST:event_btnReadFromDBActionPerformed

    private void btnEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmailActionPerformed
        email();
    }//GEN-LAST:event_btnEmailActionPerformed

    private void btnMapInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMapInfoActionPerformed
        try {
            setStatusBar(" Processing... ");
            
            AsergSurvey[] Subs = getSelectedRows();
                        
            int i=0;
            for(AsergSurvey S : Subs){
                MozillaConnection.bugzillaDevInfo(S);
                AsergSurveyDAO.updateDevInfo(S);
                
                System.out.printf("%d/%d updated...%n",++i,Subs.length);
            }
            //dtmSurvey.clear();
            readFromDb();
            setStatusBar(Subs.length+" lines updated.");

        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_btnMapInfoActionPerformed

    private void btnChangeStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeStatusActionPerformed
        try {
            setStatusBar(" Processing... ");
            
            AsergSurvey[] Subs = getSelectedRows();

            Object[] options = new String[]{"Pending","Sent","Answered","Excluded","Other","Close"};
            int Sel = JOptionPane.showOptionDialog(this, "Select the status", "Status Change", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[5]);
            if(Sel != 5){ //Não selecionou o fechar
                AsergSurveyDAO.SurveyStatus Status;
                switch(Sel){
                    case 0: Status = AsergSurveyDAO.SurveyStatus.PENDING; break;
                    case 1: Status = AsergSurveyDAO.SurveyStatus.SENT; break;
                    case 2: Status = AsergSurveyDAO.SurveyStatus.ANSWERED; break;
                    case 3: Status = AsergSurveyDAO.SurveyStatus.EXCLUDED; break;
                    case 4: Status = AsergSurveyDAO.SurveyStatus.OTHER; break;
                    default: Status = AsergSurveyDAO.SurveyStatus.OTHER;
                }
                AsergSurveyDAO.updateStatus(Status, Subs);
                
                readFromDb();
                setStatusBar(Subs.length+" lines updated.");
            }

        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_btnChangeStatusActionPerformed

    private void btnSaveAnswerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveAnswerActionPerformed
        try{
            AsergSurvey Sub = getSelectedRow();
            if (Sub != null) {
                SurveyAnswerDialog dlg = new SurveyAnswerDialog((java.awt.Frame) this.getParent(), true);
                dlg.setCodSurvey(Sub.getCodSurvey());
                dlg.setTitle(Sub.getDevLogin() + " [" + Sub.getDevName() + "]");
                dlg.setVisible(true);
    
                readFromDb();
            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_btnSaveAnswerActionPerformed

    private void btnThanksEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThanksEmailActionPerformed
        try{
            AsergSurvey Sub = getSelectedRow();
            
            if (Sub != null) {
                ThankEmailDialog dlg = new ThankEmailDialog((java.awt.Frame) this.getParent(), true);
                dlg.setSubject(Sub);
                dlg.setTitle(Sub.getDevLogin() + " [" + Sub.getDevName() + "]");
                dlg.setVisible(true);
            }
            
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_btnThanksEmailActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SurveyDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SurveyDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SurveyDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SurveyDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SurveyDialog dialog = new SurveyDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btgStatus;
    private javax.swing.JButton btnChangeStatus;
    private javax.swing.JButton btnEmail;
    private javax.swing.JButton btnMapInfo;
    private javax.swing.JButton btnReadFromDB;
    private javax.swing.JButton btnSaveAnswer;
    private javax.swing.JButton btnThanksEmail;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblStatusBar;
    private javax.swing.JRadioButton rdbAll;
    private javax.swing.JRadioButton rdbAnswered;
    private javax.swing.JRadioButton rdbExcluded;
    private javax.swing.JRadioButton rdbOther;
    private javax.swing.JRadioButton rdbPending;
    private javax.swing.JRadioButton rdbSent;
    private javax.swing.JTable tblSurveySubjects;
    private javax.swing.JTextField txfBugClause;
    private javax.swing.JFormattedTextField txfDate;
    // End of variables declaration//GEN-END:variables

    public void email(){
        try {
            
            AsergSurvey Sub = getSelectedRow();
            if(Sub!=null){
                EmailDialog dlg=new EmailDialog((java.awt.Frame)this.getParent(), true);
                dlg.setSubject(Sub);
                dlg.setVisible(true);
                
                readFromDb();
            }
            
        } catch (Exception e) {
            System.out.println(e);
        }

        
    }
    
    
    public void readFromDb(){
        try{
            char Status = getSelectedRadioStatus();
            String Date = getSearchDate();
            String BugClause = txfBugClause.getText();
            
            ArrayList<AsergSurvey> lst = AsergSurveyDAO.getSurveys(Status, Date, BugClause);

            dtmSurvey.clear();
            dtmSurvey.add(lst);
//            setTableColumnSizes();
//            javax.swing.table.TableColumn Col = null;
//            Col = tblSurveySubjects.getColumnModel().getColumn(0);
//            Col.setCellRenderer(new SurveyCellRenderer());
            
            setStatusBar(lst.size()+" items recovered.");
            this.setVisible(true);
        }catch(Exception e){
            System.out.println(e);
        }
    }
    
    public char getSelectedRadioStatus(){
        if(rdbPending.isSelected()){
            return 'p';
        }
        else if(rdbAnswered.isSelected()){
            return 'A';
        }
        else if(rdbSent.isSelected()){
            return 's';
        }
        else if(rdbExcluded.isSelected()){
            return 'e';
        }
        else if(rdbOther.isSelected()){
            return 'o';
        }
        else{
            return 0;
        }
    }
    
    public String getSearchDate(){
        return txfDate.getText();
    }
    
    public void setStatusBar(String Msg){
        lblStatusBar.setText(Msg);
    }
    
    public void setTableColumnSizes(){
        tblSurveySubjects.setAutoResizeMode( javax.swing.JTable.AUTO_RESIZE_LAST_COLUMN );
        int[] Sizes = new int[]{8,8,120,80,30,45,30,240};
        javax.swing.table.TableColumn Col = null;
        for (int i = 0; i < tblSurveySubjects.getColumnCount(); i++) {
            Col = tblSurveySubjects.getColumnModel().getColumn(i);
            Col.setPreferredWidth(Sizes[i]); 
        }
    }
    
    public AsergSurvey getSelectedRow(){
        int Row = tblSurveySubjects.convertRowIndexToModel(tblSurveySubjects.getSelectedRow());

        AsergSurvey Sub = null;
        if (Row >= 0) {
            Sub = new AsergSurvey();
            Sub.setStatus((Character) dtmSurvey.getValueAt(Row, 0));
            Sub.setCodSurvey((Integer) dtmSurvey.getValueAt(Row, 1) );
            Sub.setDevLogin( (String) dtmSurvey.getValueAt(Row, 2) );
            Sub.setDevName((String) dtmSurvey.getValueAt(Row, 3));
            Sub.setBugsResolved((Integer) dtmSurvey.getValueAt(Row, 4));
            Sub.setDtSurvey((Timestamp) dtmSurvey.getValueAt(Row, 5));
            Sub.setBugId((Integer) dtmSurvey.getValueAt(Row, 6));
            Sub.setShortDesc((String) dtmSurvey.getValueAt(Row, 7));
        }
        return Sub;
    }
    
    public AsergSurvey[] getSelectedRows(){
        int[] Rows = tblSurveySubjects.getSelectedRows();

        AsergSurvey[] Subs = new AsergSurvey[Rows.length];
        for(int i=0; i<Rows.length; i++){
            int ModelRow = tblSurveySubjects.convertRowIndexToModel(Rows[i]);
            
            Subs[i] = new AsergSurvey();
            Subs[i].setStatus((Character) dtmSurvey.getValueAt(ModelRow, 0));
            Subs[i].setCodSurvey((Integer) dtmSurvey.getValueAt(ModelRow, 1) );
            Subs[i].setDevLogin( (String) dtmSurvey.getValueAt(ModelRow, 2) );
            Subs[i].setDevName((String) dtmSurvey.getValueAt(ModelRow, 3));
            Subs[i].setBugsResolved((Integer) dtmSurvey.getValueAt(ModelRow, 4));
            Subs[i].setDtSurvey((Timestamp) dtmSurvey.getValueAt(ModelRow, 5));
            Subs[i].setBugId((Integer) dtmSurvey.getValueAt(ModelRow, 6));
            Subs[i].setShortDesc((String) dtmSurvey.getValueAt(ModelRow, 7));
        }
        return Subs;
    }
    
    private void initTableComp(){
        setTableColumnSizes();
        
        javax.swing.table.TableColumn Col = null;
        Col = tblSurveySubjects.getColumnModel().getColumn(0);
        Col.setCellRenderer(new SurveyCellRenderer());
    }

}
