/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package bugapp.gui;

import bugapp.persistence.dao.AsergSurveyAnswerDAO;
import bugapp.persistence.dao.AsergSurveyDAO;
import bugapp.persistence.entity.AsergSurveyAnswer;

/**
 *
 * @author Henrique
 */
public class SurveyAnswerDialog extends javax.swing.JDialog {
    
    private int CodSurvey;

    /**
     * Creates new form SurveyAnswerDialog
     */
    public SurveyAnswerDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgGroupQ2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        btnSave = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        pnlQuestion1 = new javax.swing.JPanel();
        pnlQ1Checks = new javax.swing.JPanel();
        chkQ1A = new javax.swing.JCheckBox();
        chkQ1B = new javax.swing.JCheckBox();
        chkQ1C = new javax.swing.JCheckBox();
        chkQ1D = new javax.swing.JCheckBox();
        chkQ1E = new javax.swing.JCheckBox();
        jScrollPane3 = new javax.swing.JScrollPane();
        txaQuestion1 = new javax.swing.JTextArea();
        pnlQuestion2 = new javax.swing.JPanel();
        pnlQ2Radios = new javax.swing.JPanel();
        rdbQ2Yes = new javax.swing.JRadioButton();
        rdbQ2No = new javax.swing.JRadioButton();
        rdbQ2Other = new javax.swing.JRadioButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        txaQuestion2 = new javax.swing.JTextArea();
        pnlQuestion3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaQuestion3 = new javax.swing.JTextArea();
        pnlQuestion4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txaQuestion4 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));

        btnSave.setText("Save and Close");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel1.add(btnSave);

        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        jPanel1.add(btnClose);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jPanel2.setLayout(new java.awt.GridLayout(4, 1));

        pnlQuestion1.setBorder(javax.swing.BorderFactory.createTitledBorder("Question 1"));
        pnlQuestion1.setLayout(new java.awt.BorderLayout());

        chkQ1A.setText("a. similar");
        pnlQ1Checks.add(chkQ1A);

        chkQ1B.setText("b. assgined to");
        pnlQ1Checks.add(chkQ1B);

        chkQ1C.setText("c. block");
        pnlQ1Checks.add(chkQ1C);

        chkQ1D.setText("d. high priority");
        pnlQ1Checks.add(chkQ1D);

        chkQ1E.setText("e. other");
        pnlQ1Checks.add(chkQ1E);

        pnlQuestion1.add(pnlQ1Checks, java.awt.BorderLayout.NORTH);

        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        txaQuestion1.setColumns(20);
        txaQuestion1.setLineWrap(true);
        txaQuestion1.setRows(5);
        jScrollPane3.setViewportView(txaQuestion1);

        pnlQuestion1.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        jPanel2.add(pnlQuestion1);

        pnlQuestion2.setLayout(new java.awt.BorderLayout());

        pnlQ2Radios.setBorder(javax.swing.BorderFactory.createTitledBorder("Question 2"));

        btgGroupQ2.add(rdbQ2Yes);
        rdbQ2Yes.setText("Yes, most I chose myself");
        pnlQ2Radios.add(rdbQ2Yes);

        btgGroupQ2.add(rdbQ2No);
        rdbQ2No.setText("No, most are assigned to me");
        pnlQ2Radios.add(rdbQ2No);

        btgGroupQ2.add(rdbQ2Other);
        rdbQ2Other.setText("Other");
        pnlQ2Radios.add(rdbQ2Other);

        pnlQuestion2.add(pnlQ2Radios, java.awt.BorderLayout.NORTH);

        jScrollPane4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane4.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        txaQuestion2.setColumns(20);
        txaQuestion2.setLineWrap(true);
        txaQuestion2.setRows(5);
        jScrollPane4.setViewportView(txaQuestion2);

        pnlQuestion2.add(jScrollPane4, java.awt.BorderLayout.CENTER);

        jPanel2.add(pnlQuestion2);

        pnlQuestion3.setBorder(javax.swing.BorderFactory.createTitledBorder("Question 3"));
        pnlQuestion3.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        txaQuestion3.setColumns(20);
        txaQuestion3.setLineWrap(true);
        txaQuestion3.setRows(5);
        jScrollPane1.setViewportView(txaQuestion3);

        pnlQuestion3.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel2.add(pnlQuestion3);

        pnlQuestion4.setBorder(javax.swing.BorderFactory.createTitledBorder("Question 4"));
        pnlQuestion4.setToolTipText("");
        pnlQuestion4.setLayout(new java.awt.BorderLayout());

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        txaQuestion4.setColumns(20);
        txaQuestion4.setLineWrap(true);
        txaQuestion4.setRows(5);
        jScrollPane2.setViewportView(txaQuestion4);

        pnlQuestion4.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jPanel2.add(pnlQuestion4);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        try{
            AsergSurveyAnswer Answer = getAnswer();
            AsergSurveyAnswerDAO.save(Answer);
            AsergSurveyDAO.updateStatus(CodSurvey, AsergSurveyDAO.SurveyStatus.ANSWERED);            
            
            this.setVisible(false);
        }catch(Exception ex){
            System.out.println(ex);
        }
        
    }//GEN-LAST:event_btnSaveActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(SurveyAnswerDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(SurveyAnswerDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(SurveyAnswerDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(SurveyAnswerDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                SurveyAnswerDialog dialog = new SurveyAnswerDialog(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btgGroupQ2;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnSave;
    private javax.swing.JCheckBox chkQ1A;
    private javax.swing.JCheckBox chkQ1B;
    private javax.swing.JCheckBox chkQ1C;
    private javax.swing.JCheckBox chkQ1D;
    private javax.swing.JCheckBox chkQ1E;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JPanel pnlQ1Checks;
    private javax.swing.JPanel pnlQ2Radios;
    private javax.swing.JPanel pnlQuestion1;
    private javax.swing.JPanel pnlQuestion2;
    private javax.swing.JPanel pnlQuestion3;
    private javax.swing.JPanel pnlQuestion4;
    private javax.swing.JRadioButton rdbQ2No;
    private javax.swing.JRadioButton rdbQ2Other;
    private javax.swing.JRadioButton rdbQ2Yes;
    private javax.swing.JTextArea txaQuestion1;
    private javax.swing.JTextArea txaQuestion2;
    private javax.swing.JTextArea txaQuestion3;
    private javax.swing.JTextArea txaQuestion4;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the CodSurvey
     */
    public int getCodSurvey() {
        return CodSurvey;
    }

    /**
     * @param CodSurvey the CodSurvey to set
     */
    public void setCodSurvey(int CodSurvey) {
        this.CodSurvey = CodSurvey;
        readFromDb();
    }
    
    public void readFromDb(){
        try{
            AsergSurveyAnswer Answer = AsergSurveyAnswerDAO.get(CodSurvey);
            if (Answer != null) {

                if (Answer.getQ1().charAt(0) == '1') {
                    chkQ1A.setSelected(true);
                }
                if (Answer.getQ1().charAt(1) == '1') {
                    chkQ1B.setSelected(true);
                }
                if (Answer.getQ1().charAt(2) == '1') {
                    chkQ1C.setSelected(true);
                }
                if (Answer.getQ1().charAt(3) == '1') {
                    chkQ1D.setSelected(true);
                }
                if (Answer.getQ1().charAt(4) == '1') {
                    chkQ1E.setSelected(true);
                }
                txaQuestion1.setText(Answer.getQ1Detail());

                if (Answer.getQ2().equals("Y")) {
                    rdbQ2Yes.setSelected(true);
                } else if (Answer.getQ2().equals("N")) {
                    rdbQ2No.setSelected(true);
                } else {
                    rdbQ2Other.setSelected(true);
                }
                txaQuestion2.setText(Answer.getQ2Detail());

                txaQuestion3.setText(Answer.getQ3());
                txaQuestion4.setText(Answer.getQ4());
            }
        }catch(Exception ex){
            System.out.println(ex);
        }
    }
    
    public AsergSurveyAnswer getAnswer(){
        AsergSurveyAnswer Answer = new AsergSurveyAnswer();
        Answer.setCodSurvey(CodSurvey);
        
        String Q1="";
        Q1+=(chkQ1A.isSelected())?"1":"0";
        Q1+=(chkQ1B.isSelected())?"1":"0";
        Q1+=(chkQ1C.isSelected())?"1":"0";
        Q1+=(chkQ1D.isSelected())?"1":"0";
        Q1+=(chkQ1E.isSelected())?"1":"0";
        Answer.setQ1(Q1);
        
        String Q2="O";
        if(rdbQ2Yes.isSelected()) Q2="Y";
        else if(rdbQ2No.isSelected()) Q2="N";
        Answer.setQ2(Q2);
        
        Answer.setQ1Detail(txaQuestion1.getText());
        Answer.setQ2Detail(txaQuestion2.getText());
        Answer.setQ3(txaQuestion3.getText());
        Answer.setQ4(txaQuestion4.getText());
        return Answer;
    }
}
